name: "Default user"
stages:
  initramfs:
  - name: "Setup user for live CD"
    files:
    - path: /etc/issue.d/99_passwd
      content: |
        Login with username=root, password=ros
    ensure_entities:
    - path: /etc/shadow
      entity: |
        kind: "shadow"
        username: "root"
        password: "ros"
